# Generated by Django 2.2.1 on 2019-06-26 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import libs.django.db.models.base_model


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GpxPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('record_time', models.DateTimeField(verbose_name='기록 시간')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('elevation', models.FloatField(verbose_name='elevation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'GPX Point',
                'verbose_name_plural': 'GPX Point 리스트',
                'db_table': 'gpx_point',
                'unique_together': {('user', 'record_time')},
            },
            bases=(libs.django.db.models.base_model.EqualizeMixin, models.Model),
        ),
    ]
