# Generated by Django 2.2.1 on 2019-06-26 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import libs.django.db.models.base_model


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpxShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('gpx_uuid', models.UUIDField(unique=True, verbose_name='GPX UUID')),
                ('start_record_time', models.DateTimeField(verbose_name='오픈 시작 기록 시간')),
                ('end_record_time', models.DateTimeField(help_text='종료 시간이 없으면 마지막 데이터까지 공유 됩니다.', null=True, verbose_name='오픈 종료 기록 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'GPX share',
                'verbose_name_plural': 'GPX share 리스트',
                'db_table': 'gpx_share',
            },
            bases=(libs.django.db.models.base_model.EqualizeMixin, libs.django.db.models.base_model.ChangeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GpxCrawlStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('crawl_url', models.TextField(verbose_name='Crawl URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'GPX Crawl Status',
                'verbose_name_plural': 'GPX Crawl Status 리스트',
                'db_table': 'gpx_crawl_status',
            },
            bases=(libs.django.db.models.base_model.EqualizeMixin, libs.django.db.models.base_model.ChangeMixin, models.Model),
        ),
    ]
