# Generated by Django 2.2.1 on 2019-06-26 14:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('location', '0003_auto_20190626_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpxshare',
            name='gpx_uuid',
        ),
        migrations.AddField(
            model_name='gpxshare',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AddField(
            model_name='gpxshare',
            name='share_uuid',
            field=models.UUIDField(default=uuid.UUID('004c7530-d53f-47db-aec6-54cea935310c'), unique=True, verbose_name='공유 UUID'),
        ),
    ]
