# Generated by Django 2.2.2 on 2019-07-20 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import libs.django.db.models.base_model
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0005_auto_20190627_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpxshare',
            name='share_uuid',
            field=models.UUIDField(default=uuid.UUID('092fd248-ac9a-4fce-a510-e4ecc0374664'), unique=True, verbose_name='공유 UUID'),
        ),
        migrations.CreateModel(
            name='ExtractGpsFromExifStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('image_path', models.FilePathField(path='/', recursive=True, verbose_name='Image 경로')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Exif 에서 GPS 정보 가져오기 상태',
                'verbose_name_plural': 'Exif 에서 GPS 정보 가져오기 상태 리스트',
                'db_table': 'extract_gps_on_exif_status',
            },
            bases=(libs.django.db.models.base_model.EqualizeMixin, libs.django.db.models.base_model.ChangeMixin, models.Model),
        ),
    ]
