# Generated by Django 2.2.2 on 2019-07-20 20:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_auto_20190721_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractgpsfromexifstatus',
            name='image_path',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/Users/antiline/Documents/Jun2/mount', recursive=True, verbose_name='Image 경로'),
        ),
        migrations.AlterField(
            model_name='gpxshare',
            name='share_uuid',
            field=models.UUIDField(default=uuid.UUID('84574781-f532-4aaa-991e-5437c65c7247'), unique=True, verbose_name='공유 UUID'),
        ),
        migrations.AlterModelTable(
            name='extractgpsfromexifstatus',
            table='extract_gps_from_exif_status',
        ),
    ]
