# Generated by Django 2.2.2 on 2019-07-21 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_auto_20190721_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxpoint',
            name='ref_type',
            field=models.IntegerField(choices=[(0, 'GPX crawl'), (1, 'Extract from exif'), (2, 'by User')], default=0, verbose_name='Point reference 타입'),
        ),
        migrations.AlterField(
            model_name='gpxshare',
            name='share_uuid',
            field=models.UUIDField(default=uuid.UUID('b5a15631-5f1f-4260-a72c-f040bb6fbbb1'), unique=True, verbose_name='공유 UUID'),
        ),
    ]
