# Generated by Django 2.2.2 on 2019-07-22 20:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_auto_20190722_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractgpsfromexifstatus',
            name='image_path',
            field=models.TextField(verbose_name='Image 경로'),
        ),
        migrations.AlterField(
            model_name='gpxshare',
            name='share_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='공유 UUID'),
        ),
    ]
